export const SET_RECORDS = '[RECORDS] SET_RECORDS';
export const SET_RECORDS_SUCCESS = '[RECORDS] SET_RECORDS_SUCCESS';
export const UPDATE_RECORD = '[RECORDS] UPDATE_RECORD';
export const ADD_RECORD = '[RECORDS] ADD_RECORD';